# http://docs.travis-ci.com/user/languages/r/
language: r

sudo: required
warnings_are_errors: true

apt_packages:
- libc-bin

env:
global:
 - NOT_CRAN=true
 
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

r_binary_packages:
- sp
